### PR TITLE
SBT 0.13.17 and SBT 1.1.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ping @eed3si9n  -- can you merge and release a new version?

**Comment by eed3si9n** [comment]
Sorry, I don't maintain sbt-onejar.

**Comment by sullis** [comment]
ping @retronym

**Comment by sullis** [comment]
ready for merge @retronym

**Comment by retronym** [comment]
I don't believe we need to make a new release here, as the artifact name for SBT 1.0 and 1.1 is identical.

**Pull request merged**
